-- Tabla de resultados de lotería
CREATE TABLE public.lottery_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  lottery_type TEXT NOT NULL,
  result_number TEXT NOT NULL,
  animal_name TEXT,
  draw_time TEXT NOT NULL,
  draw_date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Tabla de códigos de acceso
CREATE TABLE public.access_codes (
  code TEXT PRIMARY KEY,
  alias TEXT,
  is_active BOOLEAN DEFAULT true,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Tabla de pronósticos de Dato Ricardo
CREATE TABLE public.dato_ricardo_predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  lottery_type TEXT NOT NULL,
  prediction_date DATE NOT NULL,
  draw_time TEXT NOT NULL,
  predicted_numbers TEXT[] NOT NULL,
  predicted_animals TEXT[],
  notes TEXT
);

-- Tabla de pronósticos de IA
CREATE TABLE public.ai_predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  lottery_type TEXT NOT NULL,
  prediction_date DATE NOT NULL,
  predicted_numbers TEXT[] NOT NULL,
  predicted_animals TEXT[],
  confidence_score DECIMAL(5,2),
  analysis_notes TEXT
);

-- Habilitar RLS
ALTER TABLE public.lottery_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dato_ricardo_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_predictions ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público (lectura)
CREATE POLICY "Public read results" ON public.lottery_results FOR SELECT USING (true);
CREATE POLICY "Public read codes" ON public.access_codes FOR SELECT USING (true);
CREATE POLICY "Public read ricardo" ON public.dato_ricardo_predictions FOR SELECT USING (true);
CREATE POLICY "Public read ai" ON public.ai_predictions FOR SELECT USING (true);

-- Políticas de escritura pública (para admin sin auth)
CREATE POLICY "Public write results" ON public.lottery_results FOR ALL USING (true);
CREATE POLICY "Public write codes" ON public.access_codes FOR ALL USING (true);
CREATE POLICY "Public write ricardo" ON public.dato_ricardo_predictions FOR ALL USING (true);
CREATE POLICY "Public write ai" ON public.ai_predictions FOR ALL USING (true);

-- Insertar código de administrador
INSERT INTO public.access_codes (code, role, alias) VALUES ('GANADOR85', 'admin', 'Jefe');

-- Habilitar realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.lottery_results;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_predictions;